# Generated by Django 5.0.7 on 2024-10-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='codigo_plantel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='identificador',
        ),
    ]
